### ISSUE TITLE
WSS error on the front

### ISSUE THREAD

**Issue by vafanassieff** [gregoryseibert/funkwhale-docker-traefik#2]
Hello thanks for helping me doing my funkwhale setup, but i'm encountering several error in the front console and in the back with the websockets.

I'm kinda new to that bu any help would be great !

Edit : Okay the error are only for Chrome, working for Firefox

Front errors  :

`index.js:126 WebSocket connection to 'wss://s.sel.ovh/api/v1/activity?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTQxNjQ0NTc1LCJlbWFpbCI6ImFAdC5jbyIsIm9yaWdfaWF0IjoxNTQxMDM1NjU4fQ.XTvABT16OafKpkGFk9_978RvdStBS1MfrMi1d7APA4w' failed: WebSocket is closed before the connection is established.
(anonymous) @ index.js:126
setTimeout (async)
C @ index.js:124
setTimeout (async)
A @ index.js:113`

`5index.js:123 WebSocket connection to 'wss://s.sel.ovh/api/v1/activity?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTQxNjQ0NTc1LCJlbWFpbCI6ImFAdC5jbyIsIm9yaWdfaWF0IjoxNTQxMDM1NjU4fQ.XTvABT16OafKpkGFk9_978RvdStBS1MfrMi1d7APA4w' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`

Back errors : 

`
funkwhale-api         | 172.26.0.7:48228 - - [01/Nov/2018:02:43:00] "WSCONNECTING /api/v1/activity" - -
funkwhale-api         | 172.26.0.7:48228 - - [01/Nov/2018:02:43:00] "WSCONNECT /api/v1/activity" - -
funkwhale-frontend    | 172.23.0.6 - - [01/Nov/2018:02:43:00 +0000] "GET /api/v1/activity?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTQxNjQ0NTc5LCJlbWFpbCI6ImFAdC5jbyIsIm9yaWdfaWF0IjoxNTQxMDM1NjU4fQ._J9nY1wctgQ_WKGW_qZQPu7ihPIyDDHR9nElfEEyMQ4 HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
funkwhale-api         | 172.26.0.7:48228 - - [01/Nov/2018:02:43:00] "WSDISCONNECT /api/v1/activity" - -
`

Il also notice that even using it with a lets encrypt widcard certificate i still have error of image not being in HTTPS thus leading my site to be not full secured for Chrome

`vue-lazyload.js:6 Mixed Content: The page at 'https://s.sel.ovh/library/albums/1' was loaded over HTTPS, but requested an insecure image 'http://s.sel.ovh/media/__sized__/albums/covers/2018/11/01/b489a9261-c70f-4243-9e3a-602ec0ad276d-crop-c0-5__0-5-50x50-70.jpg'. This content should also be served over HTTPS.`

But the issue is the same on the offial demo site.

Cheers !

**Comment by gregoryseibert** [comment]
Hi, I'm sorry that I haven't answered for so long. I was held up by university work.
I guess that if the issue is or was really the same on the official demo site, it should't be caused by traefik.
