### ISSUE TITLE
Not an

### ISSUE THREAD

**Issue by titooo7** [gregoryseibert/funkwhale-docker-traefik#3]
Not an issue really, but what are the installation commanda once I git clone your repository and amend and edit the 4 files mentioned in the readme?

**Comment by gregoryseibert** [comment]
Hi, I'm sorry that I haven't answered for so long. I was held up by university work.
The setup steps should be the same as from the official instruction site (https://docs.funkwhale.audio/installation/docker.html) except that you use the docker-compose file and .env file from this repo. Though you should adapt them to your needs as briefly described in the readme.
