### ISSUE TITLE
help with traefik

### ISSUE THREAD

**Issue by sm0kingm4n** [gregoryseibert/funkwhale-docker-traefik#4]
i followed instructions, edited the files accordingly to my setup and i can log in into funkwhale. As soon as i log in the https stops working and went to the http (browser complaining not secure  web site).
How to fix this? I am using docker and traefik latest versions. please help. thanks.

**Comment by gregoryseibert** [comment]
Hi, I'm sorry that I haven't answered for so long. I was held up by university work.
I'm not quite sure, what could've caused your issue. But I think that it is or was an internal routing problem of funkwhale, if https was working prior to your login.
